In [1]:
import numpy as np

In [3]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])


In [4]:
add = a1 + a2
add

array([ 7,  9, 11, 13, 15])

In [5]:
sub = a1 - a2
sub

array([-5, -5, -5, -5, -5])

In [7]:
mul = a1 * a2
mul

array([ 6, 14, 24, 36, 50])

In [10]:
div = a1/a2
div

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [11]:
exp = a1**a2
exp

array([      1,     128,    6561,  262144, 9765625])

In [12]:
l = np.array([1,2,3,4,5])
l

array([1, 2, 3, 4, 5])

In [13]:
broadcast = l + 10
broadcast

array([11, 12, 13, 14, 15])

In [15]:
a = np.arange(1 , 26)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [17]:
slice = arr[:6]
slice

array([1, 2, 3, 4, 5, 6])

In [18]:
slice * 10

#shallow copy in broadcasting


array([10, 20, 30, 40, 50, 60])

In [19]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [ ]:
# deep copy in broadcasting

In [26]:
slice = a[:6]
slice

array([99,  2,  3,  4,  5,  6])

In [27]:
a.copy()

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [30]:


A = np.array([[1,2] , [3,4]])
B = np.array([[5,6] , [7,8]])


In [31]:
A

array([[1, 2],
       [3, 4]])

In [32]:
B

array([[5, 6],
       [7, 8]])

In [33]:
A @ B

array([[19, 22],
       [43, 50]])

In [34]:
np.dot(A , B)

array([[19, 22],
       [43, 50]])

In [35]:
# transpose in matrix


A.T

array([[1, 3],
       [2, 4]])

In [36]:
B.T

array([[5, 7],
       [6, 8]])

In [37]:
a = np.array([1,2,3,4,5])
b  = np.array([6,7,8,9,10])


In [38]:
np.vstack((a , b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [39]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [58]:
# splitting array

c = np.arange(1,21).reshape(5,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [59]:
np.hsplit(c , 2)


[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20]])]

In [64]:
a=np.hsplit(c , 4)

In [65]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [66]:
for i in a:
    print(i)

[[ 1]
 [ 5]
 [ 9]
 [13]
 [17]]
[[ 2]
 [ 6]
 [10]
 [14]
 [18]]
[[ 3]
 [ 7]
 [11]
 [15]
 [19]]
[[ 4]
 [ 8]
 [12]
 [16]
 [20]]
