In [2]:
import numpy as np

In [4]:
arr = np.arange(11 , 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr[5]

np.int64(16)

In [6]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
arr[:7]

array([11, 12, 13, 14, 15, 16, 17])

In [8]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [9]:
arr[3::2]

array([14, 16, 18, 20])

In [10]:

arr = np.arange(1 , 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [17]:
matrix = arr.reshape(6 , 5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [28]:
matrix[3,2]
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [25]:
slice = matrix[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [29]:
slice = matrix[1:4 ,1:3]
slice

array([[ 7,  8],
       [12, 13],
       [17, 18]])

In [30]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [34]:
bool_index = arr%2==0



In [35]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])