In [1]:
import numpy as np


In [7]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [8]:
a = [1,4,5,6]
a

[1, 4, 5, 6]

In [9]:
arr1 = np.array([1 , 2 , 4.5  , 'ramesh'])
arr1

array(['1', '2', '4.5', 'ramesh'], dtype='<U32')

In [10]:
p =  [[1,2,3] , [4,5,6] , [7,8,9]]
p

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(p)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
import numpy as np
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [17]:
arr = np.zeros((4,9))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
arr = np.ones((5,7))
arr

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [19]:
arr = np.linspace(1,4,6)
arr

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [20]:
arr = np.random.rand(20)
arr

array([0.09496573, 0.53391408, 0.84054826, 0.31725343, 0.27472466,
       0.37838745, 0.83150978, 0.16026494, 0.45187579, 0.28718014,
       0.47289501, 0.33034264, 0.27025816, 0.77157565, 0.10152543,
       0.1586018 , 0.7969624 , 0.51995218, 0.04775669, 0.56523542])

In [21]:
arr = np.random.randn(20)
arr

array([ 0.064534  , -2.9104435 ,  1.72235595,  0.19976217,  0.2865635 ,
       -1.71100085, -1.34123945,  0.84813744,  1.81325031, -2.40798678,
       -0.75893052, -0.61037268, -0.21164289,  1.06141117,  0.03989554,
        0.4410617 , -0.63193594, -0.104427  , -0.13208579, -0.95759078])

In [22]:
arr = np.random.randint(10 , 20 , 10)
arr

array([19, 15, 10, 19, 18, 18, 15, 15, 10, 15], dtype=int32)

In [23]:
l = ([1 , 2, 3] , [4,5,6] , [7,8,9])
l

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [24]:
arr = np.array(l)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr.shape



(3, 3)

In [26]:
arr.size

9

In [27]:
arr.dtype

dtype('int64')

In [28]:
arr.min()

np.int64(1)

In [29]:
arr.max()
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr.max()

np.int64(9)

In [31]:

arr.sum()

np.int64(45)

In [35]:
 np.sum(arr , axis = 0)

np.int64(45)

In [38]:
arr.argmax()


np.int64(0)

In [39]:
arr.argmin()


np.int64(0)

In [40]:
arr.argsort()

array([0])